# Generated by Django 4.2.10 on 2024-04-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0002_auto_20240327_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('creator_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
