# Generated by Django 5.0.3 on 2024-04-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0003_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=200)),
                ('assignment_percentage', models.CharField(max_length=200)),
                ('assignment_due', models.CharField(max_length=200)),
                ('class_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=200)),
                ('class_info', models.CharField(max_length=200)),
                ('class_module', models.CharField(max_length=200)),
                ('assignment_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_student_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_student_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_email', models.EmailField(max_length=200)),
            ],
        ),
    ]
