# Generated by Django 5.0.3 on 2024-04-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0004_tbl_assignment_tbl_class_tbl_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_class',
            name='assignment_id',
        ),
    ]
