# Generated by Django 5.0.3 on 2024-04-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0005_remove_tbl_class_assignment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_class',
            name='class_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbl_class',
            name='class_module',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbl_student',
            name='student_email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tbl_teacher',
            name='teacher_email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
