# Generated by Django 4.1 on 2024-04-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0006_alter_tbl_class_class_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student',
            name='student_password',
            field=models.CharField(default='pass', max_length=200),
        ),
        migrations.AddField(
            model_name='tbl_teacher',
            name='teacher_password',
            field=models.CharField(default='pass', max_length=200),
        ),
    ]
