# Generated by Django 4.1 on 2024-04-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0007_tbl_student_student_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_grade_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('assignment_id', models.IntegerField()),
                ('point', models.IntegerField()),
                ('grade', models.CharField(max_length=1)),
            ],
        ),
    ]
