# Generated by Django 4.1 on 2024-04-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0008_tbl_grade_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tbl_grade_class',
            new_name='Tbl_grade',
        ),
    ]
